spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    client-secret: ${KAKAO_CLIENT_SECRET}
    scope:
      - profile_nickname
      - account_email

auth:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessExp: ${JWT_ACCESS_EXP}
    refreshExp: ${JWT_REFRESH_EXP}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: ${SWAGGER_PATH}
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-match: /**

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
    base-url: ${AWS_S3_BASE_URL}

api:
  anthropic-key: ${ANTHROPIC_KEY}
  openai-key: ${OPENAI_KEY}
  remove-key: ${REMOVE_KEY}

management:
  server:
    port: ${MONITORING_PORT}
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: ./logs/app/server.log
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
server:
  tomcat:
    mbeanregistry:
      enabled: true
slack:
  token: ${WEBHOOK_SLACK_URL}